# Site settings
title: CHS Tech Community
email: contact@charlestontechnology.com
description: We are a community-built directory of tech resources in Charleston, SC
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://charlestontechnology.com" # the base hostname & protocol for your site
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, script, test, vendor]

# Build settings
markdown: kramdown

collections:
  people:
    # enable per-user pages? not yet!
    #output: true
    #permalink: /people/:path/
  companies:
  faqs:
